### ISSUE TITLE
Testing NetworkX library

### ISSUE THREAD

**Issue by Oriez** [Itay1990/NavigationAlgo#1]
Hey, 
I found a great library for graph manipulation in Python.

Please check out there site it is well documented, I already import the library for testing.
https://networkx.github.io/

let me know, what you guys think.

**Comment by Itay1990** [comment]
Wow,
Looks great. It does everything we need!

Let's wait for the other to approve, maybe the'll find something else.

**Comment by dorten10** [comment]
Wow
What a great lib. Thumbs up.
